media:
  - id: a1bdb0ceabc12251
    filename: karuppasami-dollar-back-png-38db6232.png
    original_name: Karuppasami Dollar Back PNG.png
    url: /assets/images/media/2026/06/karuppasami-dollar-back-png-38db6232.png
    description: ""
    context: products
    mime: image/png
    created_at: 2026-06-24T23:11:08+05:30
