<?php
declare(strict_types=1);

/**
 * Generates map.mmd: a deterministic repository index for people and agents.
 * Run: php cli/generate-code-map.php [--check]
 */

$root = dirname(__DIR__);
$output = $root . '/map.mmd';
$ignored = ['.git', 'vendor', 'node_modules', 'storage/logs', 'storage/cache', 'storage/media', '.agents/temp'];
$groups = ['app', 'api', 'views', 'assets', 'content', 'config', 'storage/schema', 'integrations', 'cli', 'tests', 'docs', '.github', '.agents'];

$paths = [];
foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)) as $file) {
    if (!$file->isFile()) continue;
    $relative = str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));
    foreach ($ignored as $prefix) {
        if ($relative === $prefix || str_starts_with($relative, $prefix . '/')) continue 2;
    }
    $paths[] = $relative;
}
sort($paths, SORT_NATURAL);

$indexed = [];
foreach ($groups as $group) {
    $members = array_values(array_filter($paths, static fn(string $path): bool => $path === $group || str_starts_with($path, $group . '/')));
    if ($members) $indexed[$group] = $members;
}
$other = array_values(array_filter($paths, static function (string $path) use ($groups): bool {
    foreach ($groups as $group) if ($path === $group || str_starts_with($path, $group . '/')) return false;
    return true;
}));
if ($other) $indexed['root'] = $other;

$lines = [
    '# AuraEdu repository map',
    '',
    '> Generated by `php cli/generate-code-map.php`. This index lists every tracked source, config, workflow, test, and documentation file; runtime, dependency, cache, and media directories are excluded.',
    '',
    '```mermaid',
    'flowchart LR',
    '  root["AuraEdu repository"]',
];
foreach ($indexed as $group => $members) {
    $id = 'g_' . preg_replace('/[^a-z0-9]/i', '_', $group);
    $lines[] = "  {$id}[\"{$group} — " . count($members) . " files\"]";
    $lines[] = "  root --> {$id}";
}
$lines[] = '```';
$lines[] = '';

foreach ($indexed as $group => $members) {
    $lines[] = '## ' . $group;
    $lines[] = '';
    foreach ($members as $path) $lines[] = '- `' . $path . '`';
    $lines[] = '';
}

// Break out the primary code surface into explicit sections so the
// map reads as a web product (routes → controllers → services → views).
$webFirst = [
    'controllers' => 'app/Controllers',
    'services'    => 'app/Services',
    'views'       => 'views',
];
foreach ($webFirst as $section => $dir) {
    $prefix = $dir . '/';
    $members = array_values(array_filter($paths, static fn(string $path): bool => str_starts_with($path, $prefix)));
    if (!$members) continue;
    $lines[] = '## ' . $section;
    $lines[] = '';
    foreach ($members as $path) $lines[] = '- `' . $path . '`';
    $lines[] = '';
}

$contents = implode("\n", $lines) . "\n";
if (($argv[1] ?? '') === '--check') {
    if (!is_file($output) || file_get_contents($output) !== $contents) {
        fwrite(STDERR, "map.mmd is out of date. Run php cli/generate-code-map.php\n");
        exit(1);
    }
    exit(0);
}
file_put_contents($output, $contents);
echo "Generated map.mmd with " . count($paths) . " indexed files.\n";
