<?php return [
    'version' => 2,
    'purpose' => 'MySQL database schema for the PHP hosting backend.',
    'collections' => [
        'users' => [
            'primary_key' => 'id',
            'owner_field' => 'email',
            'admin_managed' => false,
            'agent_context' => ['id', 'email', 'name', 'role', 'wallet_balance'],
            'fields' => [
                'id' => ['type' => 'string', 'required' => true],
                'email' => ['type' => 'email'],
                'username' => ['type' => 'string'],
                'name' => ['type' => 'string'],
                'role' => ['type' => 'enum', 'values' => ['customer', 'admin']],
                'must_change_password' => ['type' => 'boolean'],
                'password_changed_at' => ['type' => 'datetime'],
                'password_hash' => ['type' => 'secret'],
                'accepted_terms_at' => ['type' => 'datetime'],
            ],
        ],
        'addresses' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'admin_managed' => false,
            'agent_context' => [],
            'fields' => [
                'id' => ['type' => 'string', 'required' => true],
                'customer_email' => ['type' => 'email', 'required' => true],
                'name' => ['type' => 'string', 'required' => true],
                'recipient_name' => ['type' => 'string'],
                'phone' => ['type' => 'string'],
                'address' => ['type' => 'text', 'required' => true],
                'city' => ['type' => 'string', 'required' => true],
                'pincode' => ['type' => 'string', 'required' => true],
                'is_default' => ['type' => 'boolean'],
                'created_at' => ['type' => 'datetime'],
                'updated_at' => ['type' => 'datetime'],
            ],
        ],
        'products' => [
            'primary_key' => 'id',
            'admin_managed' => true,
            'media_fields' => ['image_url', 'image_urls'],
            'admin_fields' => ['slug', 'name', 'description', 'category', 'image_url', 'image_urls', 'price', 'offer_price', 'hsn_code', 'gst_rate', 'stock_status'],
            'agent_context' => ['id', 'slug', 'name', 'category', 'categories', 'price', 'offer_price', 'hsn_code', 'gst_rate', 'stock_status'],
            'fields' => [
                'id' => ['type' => 'string', 'required' => true],
                'slug' => ['type' => 'slug', 'required' => true],
                'name' => ['type' => 'string', 'required' => true],
                'description' => ['type' => 'text'],
                'category' => ['type' => 'string'],
                'categories' => ['type' => 'array', 'items' => 'string'],
                'image_url' => ['type' => 'local_or_remote_path'],
                'image_urls' => ['type' => 'array', 'items' => 'local_or_remote_path'],
                'price' => ['type' => 'number'],
                'offer_price' => ['type' => 'number'],
                'hsn_code' => ['type' => 'string'],
                'gst_rate' => ['type' => 'number'],
                'stock_status' => ['type' => 'enum', 'values' => ['in_stock', 'active', 'inactive', 'draft', 'out_of_stock']],
            ],
        ],
        'temples' => [  // TODO: rename key to 'hospitals' when MySQL table is renamed on Hostinger
            'primary_key' => 'id',
            'admin_managed' => true,
            'media_fields' => ['image_url'],
            'admin_fields' => ['name', 'description', 'image_url', 'address', 'map_url'],
            'agent_context' => ['slug', 'name', 'address', 'timings', 'phone'],
            'fields' => [
                'id' => ['type' => 'string'],
                'slug' => ['type' => 'slug', 'required' => true],
                'name' => ['type' => 'string', 'required' => true],
                'description' => ['type' => 'text'],
                'image_url' => ['type' => 'local_or_remote_path'],
                'address' => ['type' => 'text'],
                'timings' => ['type' => 'string'],
                'phone' => ['type' => 'string'],
                'map_link' => ['type' => 'url'],
                'map_embed_url' => ['type' => 'url'],
            ],
        ],
        'orders' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'admin_managed' => true,
            'agent_context' => ['id', 'customer_email', 'status', 'total', 'items', 'shipping_address', 'shipped_at', 'review_request_after_at', 'invoice_number', 'invoice_date', 'taxable_value', 'cgst_total', 'sgst_total', 'igst_total'],
            'fields' => [
                'id' => ['type' => 'string', 'required' => true],
                'customer_email' => ['type' => 'email'],
                'customer_name' => ['type' => 'string'],
                'customer_phone' => ['type' => 'string'],
                'status' => ['type' => 'enum', 'values' => ['pending', 'confirmed', 'processing', 'packed', 'shipped', 'delivered', 'cancelled']],
                'total' => ['type' => 'number'],
                'items' => ['type' => 'array'],
                'shipping_address' => ['type' => 'object'],
                'shipping_city' => ['type' => 'string'],
                'shipping_pincode' => ['type' => 'string'],
                'shipping_state' => ['type' => 'string'],
                'customer_gstin' => ['type' => 'string'],
                'tax_lines' => ['type' => 'array'],
                'taxable_value' => ['type' => 'number'],
                'cgst_total' => ['type' => 'number'],
                'sgst_total' => ['type' => 'number'],
                'igst_total' => ['type' => 'number'],
                'tax_total' => ['type' => 'number'],
                'supply_type' => ['type' => 'string'],
                'place_of_supply' => ['type' => 'string'],
                'supplier' => ['type' => 'object'],
                'invoice_sequence' => ['type' => 'number'],
                'invoice_financial_year' => ['type' => 'string'],
                'invoice_number' => ['type' => 'string'],
                'invoice_date' => ['type' => 'string'],
                'payment_id' => ['type' => 'string'],
                'payment_email_status' => ['type' => 'string'],
                'razorpay_order_id' => ['type' => 'string'],
                'stripe_session_id' => ['type' => 'string'],
                'created_at' => ['type' => 'datetime'],
                'shipped_at' => ['type' => 'datetime'],
            ],
        ],
        'appointments' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'admin_managed' => true,
            'agent_context' => ['id', 'customer_email', 'practitioner_slug', 'mode', 'status', 'credits_spent', 'created_at', 'ended_at'],
            'fields' => [
                'id' => ['type' => 'string', 'required' => true],
                'customer_email' => ['type' => 'email'],
                'practitioner_slug' => ['type' => 'slug'],
                'mode' => ['type' => 'enum', 'values' => ['booking']],
                'status' => ['type' => 'enum', 'values' => ['requested', 'queued', 'accepted', 'active', 'completed', 'declined', 'cancelled']],
                'credits_spent' => ['type' => 'number'],
                'accepted_at' => ['type' => 'datetime'],
                'started_at' => ['type' => 'datetime'],
                'ended_at' => ['type' => 'datetime'],
                'duration_seconds' => ['type' => 'number'],
                'last_activity_at' => ['type' => 'datetime'],
                'preferred_date' => ['type' => 'date'],
                'preferred_time' => ['type' => 'string'],
                'phone' => ['type' => 'string'],
                'notes' => ['type' => 'text'],
            ],
        ],
        'wallet_transactions' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'agent_context' => ['id', 'customer_email', 'type', 'credits', 'amount_rupees', 'source_id', 'note', 'created_at'],
            'fields' => [
                'id' => ['type' => 'string'],
                'customer_email' => ['type' => 'email'],
                'type' => ['type' => 'enum', 'values' => ['recharge', 'debit', 'refund', 'bonus']],
                'credits' => ['type' => 'number'],
                'amount_rupees' => ['type' => 'number'],
                'service_charge' => ['type' => 'number'],
                'tax' => ['type' => 'number'],
                'total_rupees' => ['type' => 'number'],
                'payment_id' => ['type' => 'string'],
                'source_id' => ['type' => 'string'],
                'note' => ['type' => 'text'],
                'status' => ['type' => 'enum', 'values' => ['confirmed', 'pending']],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'support_tickets' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'admin_managed' => true,
            'admin_fields' => ['customer_email', 'message', 'reply', 'context', 'status'],
            'agent_context' => ['id', 'customer_email', 'message', 'reply', 'status', 'created_at'],
            'fields' => [
                'id' => ['type' => 'string'],
                'customer_email' => ['type' => 'email'],
                'message' => ['type' => 'text'],
                'reply' => ['type' => 'text'],
                'context' => ['type' => 'text'],
                'status' => ['type' => 'enum', 'values' => ['open', 'answered', 'closed']],
                'created_at' => ['type' => 'datetime'],
                'updated_at' => ['type' => 'datetime'],
            ],
        ],
        'categories' => [
            'primary_key' => 'id',
            'admin_managed' => true,
            'media_fields' => ['image_url'],
            'admin_fields' => ['slug', 'name', 'description', 'image_url'],
            'fields' => [
                'id' => ['type' => 'string'],
                'slug' => ['type' => 'slug', 'required' => true],
                'name' => ['type' => 'string', 'required' => true],
                'description' => ['type' => 'text'],
                'image_url' => ['type' => 'local_or_remote_path'],
            ],
        ],
        'coupons' => [
            'primary_key' => 'id',
            'admin_managed' => true,
            'fields' => ['id' => ['type' => 'string'], 'code' => ['type' => 'string', 'required' => true], 'status' => ['type' => 'enum', 'values' => ['active', 'inactive']]],
        ],
        'audit_events' => [
            'primary_key' => 'id',
            'admin_managed' => false,
            'fields' => [
                'id' => ['type' => 'string'],
                'action' => ['type' => 'string'],
                'resource' => ['type' => 'string'],
                'resource_id' => ['type' => 'string'],
                'meta' => ['type' => 'object'],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'mail_queue' => [
            'primary_key' => 'id',
            'admin_managed' => false,
            'fields' => [
                'id' => ['type' => 'string'],
                'type' => ['type' => 'string'],
                'to' => ['type' => 'email'],
                'subject' => ['type' => 'string'],
                'html' => ['type' => 'text'],
                'status' => ['type' => 'enum', 'values' => ['pending', 'sent', 'failed']],
                'available_at' => ['type' => 'datetime'],
                'meta' => ['type' => 'object'],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'mail_inbox' => [
            'primary_key' => 'id',
            'admin_managed' => false,
            'fields' => [
                'id' => ['type' => 'string'],
                'from_email' => ['type' => 'email'],
                'from_name' => ['type' => 'string'],
                'to_email' => ['type' => 'string'],
                'subject' => ['type' => 'string'],
                'body' => ['type' => 'text'],
                'status' => ['type' => 'enum', 'values' => ['unread', 'read', 'archived']],
                'source' => ['type' => 'string'],
                'source_id' => ['type' => 'string'],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'mail_outbox' => [
            'primary_key' => 'id',
            'admin_managed' => false,
            'fields' => [
                'id' => ['type' => 'string'],
                'queue_id' => ['type' => 'string'],
                'to_email' => ['type' => 'email'],
                'from_email' => ['type' => 'email'],
                'subject' => ['type' => 'string'],
                'body' => ['type' => 'text'],
                'status' => ['type' => 'enum', 'values' => ['pending', 'sent', 'failed']],
                'transport' => ['type' => 'enum', 'values' => ['queued', 'php_mail', 'smtp']],
                'source' => ['type' => 'string'],
                'source_id' => ['type' => 'string'],
                'created_at' => ['type' => 'datetime'],
                'sent_at' => ['type' => 'datetime'],
                'last_error' => ['type' => 'text'],
            ],
        ],
        'reviews' => [
            'primary_key' => 'id',
            'owner_field' => 'customer_email',
            'admin_managed' => false,
            'fields' => [
                'id' => ['type' => 'string'],
                'target_type' => ['type' => 'enum', 'values' => ['practitioner', 'product']],
                'target_slug' => ['type' => 'slug'],
                'rating' => ['type' => 'number'],
                'review' => ['type' => 'text'],
                'customer_email' => ['type' => 'email'],
                'source_id' => ['type' => 'string'],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'settings' => [
            'primary_key' => null,
            'admin_managed' => true,
            'fields' => [
                'shipping_mode' => ['type' => 'enum', 'values' => ['free', 'flat']],
                'flat_rate' => ['type' => 'number'],
                'currency' => ['type' => 'string'],
                'timezone' => ['type' => 'string'],
                'admin_username' => ['type' => 'string'],
                'admin_email' => ['type' => 'email'],
                'admin_password' => ['type' => 'secret'],
            ],
        ],
        'contact_submissions' => [
            'primary_key' => 'id',
            'owner_field' => 'email',
            'admin_managed' => true,
            'admin_fields' => ['name', 'email', 'phone', 'subject', 'message', 'status'],
            'fields' => [
                'id' => ['type' => 'string'],
                'name' => ['type' => 'string', 'required' => true],
                'email' => ['type' => 'email', 'required' => true],
                'phone' => ['type' => 'string'],
                'subject' => ['type' => 'string'],
                'message' => ['type' => 'text', 'required' => true],
                'status' => ['type' => 'enum', 'values' => ['new', 'read', 'closed']],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'media_files' => [
            'primary_key' => 'id',
            'admin_managed' => true,
            'fields' => [
                'id' => ['type' => 'string'],
                'filename' => ['type' => 'string'],
                'original_name' => ['type' => 'string'],
                'url' => ['type' => 'local_or_remote_path'],
                'description' => ['type' => 'text'],
                'context' => ['type' => 'enum', 'values' => ['shared', 'products']],
                'mime' => ['type' => 'string'],
                'used_in' => ['type' => 'array', 'items' => 'object'],
                'created_at' => ['type' => 'datetime'],
            ],
        ],
        'secrets' => [
            'primary_key' => 'id',
            'admin_managed' => true,
            'fields' => [
                'id' => ['type' => 'string'],
                'iv' => ['type' => 'string'],
                'ciphertext' => ['type' => 'text'],
            ],
        ],
    ],
];
